### ISSUE TITLE
How to edit save file?

### ISSUE THREAD

**Issue by lxmymjr** [crapier/RPGMakerMVSaveEditor#2]
I have typed saves into the console to see the array, but how can I edit the values of the variables?

**Comment by crapier** [comment]
Which browser are you using?
If your using chrome you should be able to type in `saves[0] ` (or you can start from just `saves`) and then just click on the arrows to expand each attribute for the save like a tree until you find what you want (for example gold is in Object>save_data>party>_gold). Once you get to the value you want to edit just double click on the value to edit it. This can be an number, string, or Boolean in general. 

For Firefox it is almost the same except you must first click on the Object text (it should be underlined when you hover over it showing that its clickable) and this will open up an object viewer in a sub window where you can expand and find what you want to edit.

After your done then you just hit save to export the modified save file. 

If you had a question about where specific values are I could answer that for you as well.

**Comment by crapier** [comment]
Alternatively you can pull the new commit and use the Ace Editors to make your changes (the old method will still work as well)

**Comment by lxmymjr** [comment]
Thank you for your instruction. But I find that I cannot edit any value in Object->save_data->variables->_data. For other value, such as _gold, the editor works well.
PS: I use chrome.

**Comment by crapier** [comment]
Hmm, yes it appears those aren't editable via the Object tree in chrome. You can alway find what you want to edit, then assign it manually. For example to edit variable 1 you can type into the console `saves[0].save_data.variables._data[1] = 100` would assign 100 to the first variable for the game. 

Or if you download the recent commit, everything is editable as plain text (in JSON format) in the Ace editor.

![Editor Pic](http://i.imgur.com/qbWQ1ww.png)

**Comment by lxmymjr** [comment]
Thank you! Both approaches work well!
